// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// GiniSimpson_DeepState_TestHarness_generation.cpp and GiniSimpson_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double GiniSimpson(NumericVector counts);

TEST(,){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector counts  = RcppDeepState_NumericVector();
  std::string counts_t = "/home/akhila/fuzzer_packages/fuzzedpackages/polyRAD/inst/testfiles/GiniSimpson/AFL_GiniSimpson/afl_inputs/" + std::to_string(t) + "_counts.qs";
  qs::c_qsave(counts,counts_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "counts values: "<< counts << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    GiniSimpson(counts);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
