// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// jsDist_DeepState_TestHarness_generation.cpp and jsDist_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::mat jsDist(const arma::mat& m, int ncores);

TEST(,){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  std::ofstream m_stream;
  arma::mat m  = RcppDeepState_mat();
  m_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/pagoda2/inst/testfiles/jsDist/inputs/m");
  m_stream << m;
  std::cout << "m values: "<< m << std::endl;
  m_stream.close();
  IntegerVector ncores(1);
  ncores[0]  = RcppDeepState_int();
  std::string ncores_t = "/home/akhila/fuzzer_packages/fuzzedpackages/pagoda2/inst/testfiles/jsDist/AFL_jsDist/afl_inputs/" + std::to_string(t) + "_ncores.qs";
  qs::c_qsave(ncores,ncores_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ncores values: "<< ncores << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    jsDist(m,ncores[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
