// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// Pnm_locus_DeepState_TestHarness_generation.cpp and Pnm_locus_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector Pnm_locus(int m, double theta, NumericVector alleleProbs);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector m(1);
  m[0]  = RcppDeepState_int();
  std::string m_t = "/home/akhila/fuzzer_packages/fuzzedpackages/DNAtools/inst/testfiles/Pnm_locus/libFuzzer_Pnm_locus/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_m.qs";
  qs::c_qsave(m,m_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "m values: "<< m << std::endl;
  NumericVector theta(1);
  theta[0]  = RcppDeepState_double();
  std::string theta_t = "/home/akhila/fuzzer_packages/fuzzedpackages/DNAtools/inst/testfiles/Pnm_locus/libFuzzer_Pnm_locus/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_theta.qs";
  qs::c_qsave(theta,theta_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "theta values: "<< theta << std::endl;
  NumericVector alleleProbs  = RcppDeepState_NumericVector();
  std::string alleleProbs_t = "/home/akhila/fuzzer_packages/fuzzedpackages/DNAtools/inst/testfiles/Pnm_locus/libFuzzer_Pnm_locus/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_alleleProbs.qs";
  qs::c_qsave(alleleProbs,alleleProbs_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "alleleProbs values: "<< alleleProbs << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    Pnm_locus(m[0],theta[0],alleleProbs);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
