// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// HoOneParent_DeepState_TestHarness_generation.cpp and HoOneParent_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector HoOneParent(IntegerVector genotypes, IntegerVector alleles2loc, IntegerVector keeploc, double ploidy);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector genotypes  = RcppDeepState_IntegerVector();
  qs::c_qsave(genotypes,"/home/akhila/fuzzer_packages/fuzzedpackages/polyRAD/inst/testfiles/HoOneParent/inputs/genotypes.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "genotypes values: "<< genotypes << std::endl;
  IntegerVector alleles2loc  = RcppDeepState_IntegerVector();
  qs::c_qsave(alleles2loc,"/home/akhila/fuzzer_packages/fuzzedpackages/polyRAD/inst/testfiles/HoOneParent/inputs/alleles2loc.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "alleles2loc values: "<< alleles2loc << std::endl;
  IntegerVector keeploc  = RcppDeepState_IntegerVector();
  qs::c_qsave(keeploc,"/home/akhila/fuzzer_packages/fuzzedpackages/polyRAD/inst/testfiles/HoOneParent/inputs/keeploc.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "keeploc values: "<< keeploc << std::endl;
  NumericVector ploidy(1);
  ploidy[0]  = RcppDeepState_double();
  qs::c_qsave(ploidy,"/home/akhila/fuzzer_packages/fuzzedpackages/polyRAD/inst/testfiles/HoOneParent/inputs/ploidy.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ploidy values: "<< ploidy << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    HoOneParent(genotypes,alleles2loc,keeploc,ploidy[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
