// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// tree_search_rcpp_DeepState_TestHarness_generation.cpp and tree_search_rcpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::List tree_search_rcpp(const Rcpp::NumericMatrix& X, const Rcpp::NumericMatrix& Y, int depth, int split_step);

TEST(,){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix X  = RcppDeepState_NumericMatrix();
  std::string X_t = "/home/akhila/fuzzer_packages/fuzzedpackages/policytree/inst/testfiles/tree_search_rcpp/AFL_tree_search_rcpp/afl_inputs/" + std::to_string(t) + "_X.qs";
  qs::c_qsave(X,X_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "X values: "<< X << std::endl;
  NumericMatrix Y  = RcppDeepState_NumericMatrix();
  std::string Y_t = "/home/akhila/fuzzer_packages/fuzzedpackages/policytree/inst/testfiles/tree_search_rcpp/AFL_tree_search_rcpp/afl_inputs/" + std::to_string(t) + "_Y.qs";
  qs::c_qsave(Y,Y_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Y values: "<< Y << std::endl;
  IntegerVector depth(1);
  depth[0]  = RcppDeepState_int();
  std::string depth_t = "/home/akhila/fuzzer_packages/fuzzedpackages/policytree/inst/testfiles/tree_search_rcpp/AFL_tree_search_rcpp/afl_inputs/" + std::to_string(t) + "_depth.qs";
  qs::c_qsave(depth,depth_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "depth values: "<< depth << std::endl;
  IntegerVector split_step(1);
  split_step[0]  = RcppDeepState_int();
  std::string split_step_t = "/home/akhila/fuzzer_packages/fuzzedpackages/policytree/inst/testfiles/tree_search_rcpp/AFL_tree_search_rcpp/afl_inputs/" + std::to_string(t) + "_split_step.qs";
  qs::c_qsave(split_step,split_step_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "split_step values: "<< split_step << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    tree_search_rcpp(X,Y,depth[0],split_step[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
