// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// Prob_DeepState_TestHarness_generation.cpp and Prob_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector Prob(CharacterVector vstrCombs, NumericVector q, NumericVector R, double r, double t);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  CharacterVector vstrCombs  = RcppDeepState_CharacterVector();
  qs::c_qsave(vstrCombs,"/home/akhila/fuzzer_packages/fuzzedpackages/DNAtools/inst/testfiles/Prob/inputs/vstrCombs.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "vstrCombs values: "<< vstrCombs << std::endl;
  NumericVector q  = RcppDeepState_NumericVector();
  qs::c_qsave(q,"/home/akhila/fuzzer_packages/fuzzedpackages/DNAtools/inst/testfiles/Prob/inputs/q.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "q values: "<< q << std::endl;
  NumericVector R  = RcppDeepState_NumericVector();
  qs::c_qsave(R,"/home/akhila/fuzzer_packages/fuzzedpackages/DNAtools/inst/testfiles/Prob/inputs/R.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "R values: "<< R << std::endl;
  NumericVector r(1);
  r[0]  = RcppDeepState_double();
  qs::c_qsave(r,"/home/akhila/fuzzer_packages/fuzzedpackages/DNAtools/inst/testfiles/Prob/inputs/r.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "r values: "<< r << std::endl;
  NumericVector t(1);
  t[0]  = RcppDeepState_double();
  qs::c_qsave(t,"/home/akhila/fuzzer_packages/fuzzedpackages/DNAtools/inst/testfiles/Prob/inputs/t.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "t values: "<< t << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    Prob(vstrCombs,q,R,r[0],t[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
