// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// makegkcpp_DeepState_TestHarness_generation.cpp and makegkcpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List makegkcpp(int cc, int kk, int mm, int detectfn, int sigmai, const NumericMatrix openval, const NumericMatrix traps, const NumericMatrix mask);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector cc(1);
  cc[0]  = RcppDeepState_int();
  qs::c_qsave(cc,"/home/akhila/fuzzer_packages/fuzzedpackages/openCR/inst/testfiles/makegkcpp/inputs/cc.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "cc values: "<< cc << std::endl;
  IntegerVector kk(1);
  kk[0]  = RcppDeepState_int();
  qs::c_qsave(kk,"/home/akhila/fuzzer_packages/fuzzedpackages/openCR/inst/testfiles/makegkcpp/inputs/kk.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "kk values: "<< kk << std::endl;
  IntegerVector mm(1);
  mm[0]  = RcppDeepState_int();
  qs::c_qsave(mm,"/home/akhila/fuzzer_packages/fuzzedpackages/openCR/inst/testfiles/makegkcpp/inputs/mm.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mm values: "<< mm << std::endl;
  IntegerVector detectfn(1);
  detectfn[0]  = RcppDeepState_int();
  qs::c_qsave(detectfn,"/home/akhila/fuzzer_packages/fuzzedpackages/openCR/inst/testfiles/makegkcpp/inputs/detectfn.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "detectfn values: "<< detectfn << std::endl;
  IntegerVector sigmai(1);
  sigmai[0]  = RcppDeepState_int();
  qs::c_qsave(sigmai,"/home/akhila/fuzzer_packages/fuzzedpackages/openCR/inst/testfiles/makegkcpp/inputs/sigmai.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "sigmai values: "<< sigmai << std::endl;
  NumericMatrix openval  = RcppDeepState_NumericMatrix();
  qs::c_qsave(openval,"/home/akhila/fuzzer_packages/fuzzedpackages/openCR/inst/testfiles/makegkcpp/inputs/openval.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "openval values: "<< openval << std::endl;
  NumericMatrix traps  = RcppDeepState_NumericMatrix();
  qs::c_qsave(traps,"/home/akhila/fuzzer_packages/fuzzedpackages/openCR/inst/testfiles/makegkcpp/inputs/traps.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "traps values: "<< traps << std::endl;
  NumericMatrix mask  = RcppDeepState_NumericMatrix();
  qs::c_qsave(mask,"/home/akhila/fuzzer_packages/fuzzedpackages/openCR/inst/testfiles/makegkcpp/inputs/mask.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mask values: "<< mask << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    makegkcpp(cc[0],kk[0],mm[0],detectfn[0],sigmai[0],openval,traps,mask);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
