// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// arma_mat_cor_DeepState_TestHarness_generation.cpp and arma_mat_cor_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::mat arma_mat_cor(const arma::mat& m);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  std::ofstream m_stream;
  arma::mat m  = RcppDeepState_mat();
  m_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/pagoda2/inst/testfiles/arma_mat_cor/inputs/m");
  m_stream << m;
  std::cout << "m values: "<< m << std::endl;
  m_stream.close();
  std::cout << "input ends" << std::endl;
  try{
    arma_mat_cor(m);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
