# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

constituerGrappes <- function(iNbObsMin, mEffectifs) {
    .Call(`_btb_constituerGrappes`, iNbObsMin, mEffectifs)
}

coordonneesGrappe <- function(iNiveauMax, iNoGrappe) {
    .Call(`_btb_coordonneesGrappe`, iNiveauMax, iNoGrappe)
}

constituerMatriceEffectifs <- function(vLigneObservation, vColonneObservation) {
    .Call(`_btb_constituerMatriceEffectifs`, vLigneObservation, vColonneObservation)
}

calculeQuantiles <- function(vModalites, vPonderation, vQuantiles) {
    .Call(`_btb_calculeQuantiles`, vModalites, vPonderation, vQuantiles)
}

rcppLissageMedian <- function(vXobservations, vYobservations, iRayon, mVar, vXCentroides, vYCentroides, vQuantiles) {
    .Call(`_btb_rcppLissageMedian`, vXobservations, vYobservations, iRayon, mVar, vXCentroides, vYCentroides, vQuantiles)
}

rcppLissage <- function(vXObservation, vYObservation, vLigneObservation, vColonneObservation, iPas, iRayon, iNeighbor, mVariables, iNumberCols, iNumberRows, iMinXCentroide, iMinYCentroide, mIcentroide, iNbCentroides, updateProgress = NULL) {
    .Call(`_btb_rcppLissage`, vXObservation, vYObservation, vLigneObservation, vColonneObservation, iPas, iRayon, iNeighbor, mVariables, iNumberCols, iNumberRows, iMinXCentroide, iMinYCentroide, mIcentroide, iNbCentroides, updateProgress)
}

rcppLissageMedianGrappe <- function(iMinObsGrappe, vXObservation, vYObservation, vLigneObservation, vColonneObservation, iPas, iRayon, mVariables, vXCentroide, vYCentroide, vLigneCentroide, vColonneCentroide, vQuantile) {
    .Call(`_btb_rcppLissageMedianGrappe`, iMinObsGrappe, vXObservation, vYObservation, vLigneObservation, vColonneObservation, iPas, iRayon, mVariables, vXCentroide, vYCentroide, vLigneCentroide, vColonneCentroide, vQuantile)
}

