// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// getFini_DeepState_TestHarness_generation.cpp and getFini_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::vec getFini(const arma::mat& Z, const int& k);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  std::ofstream Z_stream;
  arma::mat Z  = RcppDeepState_mat();
  Z_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/gdpc/inst/testfiles/getFini/inputs/Z");
  Z_stream << Z;
  std::cout << "Z values: "<< Z << std::endl;
  Z_stream.close();
  IntegerVector k(1);
  k[0]  = RcppDeepState_int();
  qs::c_qsave(k,"/home/akhila/fuzzer_packages/fuzzedpackages/gdpc/inst/testfiles/getFini/inputs/k.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "k values: "<< k << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    getFini(Z,k[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
