// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// PCH0secrjcpp_DeepState_TestHarness_generation.cpp and PCH0secrjcpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector PCH0secrjcpp(int type, int x, int nc, int jj, const IntegerVector cumss, int kk, int mm, int cc0, const IntegerVector PIA0, const NumericVector gk0, int binomN, const NumericMatrix Tsk);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector type(1);
  type[0]  = RcppDeepState_int();
  qs::c_qsave(type,"/home/akhila/fuzzer_packages/fuzzedpackages/openCR/inst/testfiles/PCH0secrjcpp/inputs/type.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "type values: "<< type << std::endl;
  IntegerVector x(1);
  x[0]  = RcppDeepState_int();
  qs::c_qsave(x,"/home/akhila/fuzzer_packages/fuzzedpackages/openCR/inst/testfiles/PCH0secrjcpp/inputs/x.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  IntegerVector nc(1);
  nc[0]  = RcppDeepState_int();
  qs::c_qsave(nc,"/home/akhila/fuzzer_packages/fuzzedpackages/openCR/inst/testfiles/PCH0secrjcpp/inputs/nc.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nc values: "<< nc << std::endl;
  IntegerVector jj(1);
  jj[0]  = RcppDeepState_int();
  qs::c_qsave(jj,"/home/akhila/fuzzer_packages/fuzzedpackages/openCR/inst/testfiles/PCH0secrjcpp/inputs/jj.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "jj values: "<< jj << std::endl;
  IntegerVector cumss  = RcppDeepState_IntegerVector();
  qs::c_qsave(cumss,"/home/akhila/fuzzer_packages/fuzzedpackages/openCR/inst/testfiles/PCH0secrjcpp/inputs/cumss.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "cumss values: "<< cumss << std::endl;
  IntegerVector kk(1);
  kk[0]  = RcppDeepState_int();
  qs::c_qsave(kk,"/home/akhila/fuzzer_packages/fuzzedpackages/openCR/inst/testfiles/PCH0secrjcpp/inputs/kk.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "kk values: "<< kk << std::endl;
  IntegerVector mm(1);
  mm[0]  = RcppDeepState_int();
  qs::c_qsave(mm,"/home/akhila/fuzzer_packages/fuzzedpackages/openCR/inst/testfiles/PCH0secrjcpp/inputs/mm.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mm values: "<< mm << std::endl;
  IntegerVector cc0(1);
  cc0[0]  = RcppDeepState_int();
  qs::c_qsave(cc0,"/home/akhila/fuzzer_packages/fuzzedpackages/openCR/inst/testfiles/PCH0secrjcpp/inputs/cc0.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "cc0 values: "<< cc0 << std::endl;
  IntegerVector PIA0  = RcppDeepState_IntegerVector();
  qs::c_qsave(PIA0,"/home/akhila/fuzzer_packages/fuzzedpackages/openCR/inst/testfiles/PCH0secrjcpp/inputs/PIA0.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "PIA0 values: "<< PIA0 << std::endl;
  NumericVector gk0  = RcppDeepState_NumericVector();
  qs::c_qsave(gk0,"/home/akhila/fuzzer_packages/fuzzedpackages/openCR/inst/testfiles/PCH0secrjcpp/inputs/gk0.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "gk0 values: "<< gk0 << std::endl;
  IntegerVector binomN(1);
  binomN[0]  = RcppDeepState_int();
  qs::c_qsave(binomN,"/home/akhila/fuzzer_packages/fuzzedpackages/openCR/inst/testfiles/PCH0secrjcpp/inputs/binomN.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "binomN values: "<< binomN << std::endl;
  NumericMatrix Tsk  = RcppDeepState_NumericMatrix();
  qs::c_qsave(Tsk,"/home/akhila/fuzzer_packages/fuzzedpackages/openCR/inst/testfiles/PCH0secrjcpp/inputs/Tsk.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Tsk values: "<< Tsk << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    PCH0secrjcpp(type[0],x[0],nc[0],jj[0],cumss,kk[0],mm[0],cc0[0],PIA0,gk0,binomN[0],Tsk);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
