// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// generateCompositions_DeepState_TestHarness_generation.cpp and generateCompositions_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List generateCompositions(int numContributors);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector numContributors(1);
  numContributors[0]  = RcppDeepState_int();
  std::string numContributors_t = "/home/akhila/fuzzer_packages/fuzzedpackages/DNAtools/inst/testfiles/generateCompositions/libFuzzer_generateCompositions/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_numContributors.qs";
  qs::c_qsave(numContributors,numContributors_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "numContributors values: "<< numContributors << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    generateCompositions(numContributors[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
