// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// gibbs_DeepState_TestHarness_generation.cpp and gibbs_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::List gibbs(Rcpp::IntegerVector U0, Rcpp::NumericVector ftgrid, Rcpp::NumericVector time, Rcpp::IntegerVector status, double a_rates, double b_rates, int cohesion, double a_beta, double b_beta, int npost, int nburnin, int nlag);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector U0  = RcppDeepState_IntegerVector();
  std::string U0_t = "/home/akhila/fuzzer_packages/fuzzedpackages/peppm/inst/testfiles/gibbs/libFuzzer_gibbs/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_U0.qs";
  qs::c_qsave(U0,U0_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "U0 values: "<< U0 << std::endl;
  NumericVector ftgrid  = RcppDeepState_NumericVector();
  std::string ftgrid_t = "/home/akhila/fuzzer_packages/fuzzedpackages/peppm/inst/testfiles/gibbs/libFuzzer_gibbs/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_ftgrid.qs";
  qs::c_qsave(ftgrid,ftgrid_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ftgrid values: "<< ftgrid << std::endl;
  NumericVector time  = RcppDeepState_NumericVector();
  std::string time_t = "/home/akhila/fuzzer_packages/fuzzedpackages/peppm/inst/testfiles/gibbs/libFuzzer_gibbs/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_time.qs";
  qs::c_qsave(time,time_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "time values: "<< time << std::endl;
  IntegerVector status  = RcppDeepState_IntegerVector();
  std::string status_t = "/home/akhila/fuzzer_packages/fuzzedpackages/peppm/inst/testfiles/gibbs/libFuzzer_gibbs/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_status.qs";
  qs::c_qsave(status,status_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "status values: "<< status << std::endl;
  NumericVector a_rates(1);
  a_rates[0]  = RcppDeepState_double();
  std::string a_rates_t = "/home/akhila/fuzzer_packages/fuzzedpackages/peppm/inst/testfiles/gibbs/libFuzzer_gibbs/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_a_rates.qs";
  qs::c_qsave(a_rates,a_rates_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "a_rates values: "<< a_rates << std::endl;
  NumericVector b_rates(1);
  b_rates[0]  = RcppDeepState_double();
  std::string b_rates_t = "/home/akhila/fuzzer_packages/fuzzedpackages/peppm/inst/testfiles/gibbs/libFuzzer_gibbs/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_b_rates.qs";
  qs::c_qsave(b_rates,b_rates_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "b_rates values: "<< b_rates << std::endl;
  IntegerVector cohesion(1);
  cohesion[0]  = RcppDeepState_int();
  std::string cohesion_t = "/home/akhila/fuzzer_packages/fuzzedpackages/peppm/inst/testfiles/gibbs/libFuzzer_gibbs/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_cohesion.qs";
  qs::c_qsave(cohesion,cohesion_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "cohesion values: "<< cohesion << std::endl;
  NumericVector a_beta(1);
  a_beta[0]  = RcppDeepState_double();
  std::string a_beta_t = "/home/akhila/fuzzer_packages/fuzzedpackages/peppm/inst/testfiles/gibbs/libFuzzer_gibbs/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_a_beta.qs";
  qs::c_qsave(a_beta,a_beta_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "a_beta values: "<< a_beta << std::endl;
  NumericVector b_beta(1);
  b_beta[0]  = RcppDeepState_double();
  std::string b_beta_t = "/home/akhila/fuzzer_packages/fuzzedpackages/peppm/inst/testfiles/gibbs/libFuzzer_gibbs/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_b_beta.qs";
  qs::c_qsave(b_beta,b_beta_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "b_beta values: "<< b_beta << std::endl;
  IntegerVector npost(1);
  npost[0]  = RcppDeepState_int();
  std::string npost_t = "/home/akhila/fuzzer_packages/fuzzedpackages/peppm/inst/testfiles/gibbs/libFuzzer_gibbs/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_npost.qs";
  qs::c_qsave(npost,npost_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "npost values: "<< npost << std::endl;
  IntegerVector nburnin(1);
  nburnin[0]  = RcppDeepState_int();
  std::string nburnin_t = "/home/akhila/fuzzer_packages/fuzzedpackages/peppm/inst/testfiles/gibbs/libFuzzer_gibbs/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_nburnin.qs";
  qs::c_qsave(nburnin,nburnin_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nburnin values: "<< nburnin << std::endl;
  IntegerVector nlag(1);
  nlag[0]  = RcppDeepState_int();
  std::string nlag_t = "/home/akhila/fuzzer_packages/fuzzedpackages/peppm/inst/testfiles/gibbs/libFuzzer_gibbs/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_nlag.qs";
  qs::c_qsave(nlag,nlag_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nlag values: "<< nlag << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    gibbs(U0,ftgrid,time,status,a_rates[0],b_rates[0],cohesion[0],a_beta[0],b_beta[0],npost[0],nburnin[0],nlag[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
