// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// clusterStat_DeepState_TestHarness_generation.cpp and clusterStat_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List clusterStat(NumericVector trueGroup, NumericVector group);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector trueGroup  = RcppDeepState_NumericVector();
  std::string trueGroup_t = "/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/clusterStat/libFuzzer_clusterStat/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_trueGroup.qs";
  qs::c_qsave(trueGroup,trueGroup_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "trueGroup values: "<< trueGroup << std::endl;
  NumericVector group  = RcppDeepState_NumericVector();
  std::string group_t = "/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/clusterStat/libFuzzer_clusterStat/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_group.qs";
  qs::c_qsave(group,group_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "group values: "<< group << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    clusterStat(trueGroup,group);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
