// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// computeConfBand__DeepState_TestHarness_generation.cpp and computeConfBand__DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::vec computeConfBand_(const arma::mat& diffCovMat, double confLevel);

TEST(,){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  std::ofstream diffCovMat_stream;
  arma::mat diffCovMat  = RcppDeepState_mat();
  diffCovMat_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/DSWE/inst/testfiles/computeConfBand_/inputs/diffCovMat");
  diffCovMat_stream << diffCovMat;
  std::cout << "diffCovMat values: "<< diffCovMat << std::endl;
  diffCovMat_stream.close();
  NumericVector confLevel(1);
  confLevel[0]  = RcppDeepState_double();
  std::string confLevel_t = "/home/akhila/fuzzer_packages/fuzzedpackages/DSWE/inst/testfiles/computeConfBand_/AFL_computeConfBand_/afl_inputs/" + std::to_string(t) + "_confLevel.qs";
  qs::c_qsave(confLevel,confLevel_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "confLevel values: "<< confLevel << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    computeConfBand_(diffCovMat,confLevel[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
