// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// calc_auc_DeepState_TestHarness_generation.cpp and calc_auc_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::List calc_auc(const Rcpp::NumericVector& xs, const Rcpp::NumericVector& ys);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector xs  = RcppDeepState_NumericVector();
  qs::c_qsave(xs,"/home/akhila/fuzzer_packages/fuzzedpackages/precrec/inst/testfiles/calc_auc/inputs/xs.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "xs values: "<< xs << std::endl;
  NumericVector ys  = RcppDeepState_NumericVector();
  qs::c_qsave(ys,"/home/akhila/fuzzer_packages/fuzzedpackages/precrec/inst/testfiles/calc_auc/inputs/ys.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ys values: "<< ys << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    calc_auc(xs,ys);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
