// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// project_to_curve_DeepState_TestHarness_generation.cpp and project_to_curve_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List project_to_curve(const NumericMatrix& x, NumericMatrix s, const double stretch);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix x  = RcppDeepState_NumericMatrix();
  std::string x_t = "/home/akhila/fuzzer_packages/fuzzedpackages/princurve/inst/testfiles/project_to_curve/libFuzzer_project_to_curve/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x.qs";
  qs::c_qsave(x,x_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericMatrix s  = RcppDeepState_NumericMatrix();
  std::string s_t = "/home/akhila/fuzzer_packages/fuzzedpackages/princurve/inst/testfiles/project_to_curve/libFuzzer_project_to_curve/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_s.qs";
  qs::c_qsave(s,s_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "s values: "<< s << std::endl;
  NumericVector stretch(1);
  stretch[0]  = RcppDeepState_double();
  std::string s_t = "/home/akhila/fuzzer_packages/fuzzedpackages/princurve/inst/testfiles/project_to_curve/libFuzzer_project_to_curve/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_s.qs";
  std::string stretch_t = "/home/akhila/fuzzer_packages/fuzzedpackages/princurve/inst/testfiles/project_to_curve/libFuzzer_project_to_curve/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_stretch.qs";
  qs::c_qsave(stretch,stretch_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "stretch values: "<< stretch << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    project_to_curve(x,s,stretch[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
