// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// myfind_DeepState_TestHarness_generation.cpp and myfind_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::uvec myfind(IntegerVector evec, int e);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector evec  = RcppDeepState_IntegerVector();
  qs::c_qsave(evec,"/home/akhila/fuzzer_packages/fuzzedpackages/BCSub/inst/testfiles/myfind/inputs/evec.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "evec values: "<< evec << std::endl;
  IntegerVector e(1);
  e[0]  = RcppDeepState_int();
  qs::c_qsave(e,"/home/akhila/fuzzer_packages/fuzzedpackages/BCSub/inst/testfiles/myfind/inputs/e.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "e values: "<< e << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    myfind(evec,e[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
