// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// enums_types_DeepState_TestHarness_generation.cpp and enums_types_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::List enums_types(int maximum);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector maximum(1);
  maximum[0]  = RcppDeepState_int();
  std::string maximum_t = "/home/akhila/fuzzer_packages/fuzzedpackages/opencv/inst/testfiles/enums_types/libFuzzer_enums_types/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_maximum.qs";
  qs::c_qsave(maximum,maximum_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "maximum values: "<< maximum << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    enums_types(maximum[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
