// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// nearbyPointsGreedyCluster_DeepState_TestHarness_generation.cpp and nearbyPointsGreedyCluster_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerVector nearbyPointsGreedyCluster(NumericVector p, double windowSize);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector p  = RcppDeepState_NumericVector();
  std::string p_t = "/home/akhila/fuzzer_packages/fuzzedpackages/pagoda2/inst/testfiles/nearbyPointsGreedyCluster/libFuzzer_nearbyPointsGreedyCluster/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_p.qs";
  qs::c_qsave(p,p_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "p values: "<< p << std::endl;
  NumericVector windowSize(1);
  windowSize[0]  = RcppDeepState_double();
  std::string windowSize_t = "/home/akhila/fuzzer_packages/fuzzedpackages/pagoda2/inst/testfiles/nearbyPointsGreedyCluster/libFuzzer_nearbyPointsGreedyCluster/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_windowSize.qs";
  qs::c_qsave(windowSize,windowSize_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "windowSize values: "<< windowSize << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    nearbyPointsGreedyCluster(p,windowSize[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
