// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// null_mle_cox_DeepState_TestHarness_generation.cpp and null_mle_cox_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::NumericVector null_mle_cox(arma::mat& XX, int n, int p, int cons, double a, double b, double csr, int niters);

TEST(,){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  std::ofstream XX_stream;
  arma::mat XX  = RcppDeepState_mat();
  XX_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/BVSNLP/inst/testfiles/null_mle_cox/inputs/XX");
  XX_stream << XX;
  std::cout << "XX values: "<< XX << std::endl;
  XX_stream.close();
  IntegerVector n(1);
  n[0]  = RcppDeepState_int();
  std::string n_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BVSNLP/inst/testfiles/null_mle_cox/AFL_null_mle_cox/afl_inputs/" + std::to_string(t) + "_n.qs";
  qs::c_qsave(n,n_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n values: "<< n << std::endl;
  IntegerVector p(1);
  p[0]  = RcppDeepState_int();
  std::string p_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BVSNLP/inst/testfiles/null_mle_cox/AFL_null_mle_cox/afl_inputs/" + std::to_string(t) + "_p.qs";
  qs::c_qsave(p,p_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "p values: "<< p << std::endl;
  IntegerVector cons(1);
  cons[0]  = RcppDeepState_int();
  std::string cons_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BVSNLP/inst/testfiles/null_mle_cox/AFL_null_mle_cox/afl_inputs/" + std::to_string(t) + "_cons.qs";
  qs::c_qsave(cons,cons_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "cons values: "<< cons << std::endl;
  NumericVector a(1);
  a[0]  = RcppDeepState_double();
  std::string a_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BVSNLP/inst/testfiles/null_mle_cox/AFL_null_mle_cox/afl_inputs/" + std::to_string(t) + "_a.qs";
  qs::c_qsave(a,a_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "a values: "<< a << std::endl;
  NumericVector b(1);
  b[0]  = RcppDeepState_double();
  std::string b_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BVSNLP/inst/testfiles/null_mle_cox/AFL_null_mle_cox/afl_inputs/" + std::to_string(t) + "_b.qs";
  qs::c_qsave(b,b_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "b values: "<< b << std::endl;
  NumericVector csr(1);
  csr[0]  = RcppDeepState_double();
  std::string csr_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BVSNLP/inst/testfiles/null_mle_cox/AFL_null_mle_cox/afl_inputs/" + std::to_string(t) + "_csr.qs";
  qs::c_qsave(csr,csr_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "csr values: "<< csr << std::endl;
  IntegerVector niters(1);
  niters[0]  = RcppDeepState_int();
  std::string n_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BVSNLP/inst/testfiles/null_mle_cox/AFL_null_mle_cox/afl_inputs/" + std::to_string(t) + "_n.qs";
  std::string niters_t = "/home/akhila/fuzzer_packages/fuzzedpackages/BVSNLP/inst/testfiles/null_mle_cox/AFL_null_mle_cox/afl_inputs/" + std::to_string(t) + "_niters.qs";
  qs::c_qsave(niters,niters_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "niters values: "<< niters << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    null_mle_cox(XX,n[0],p[0],cons[0],a[0],b[0],csr[0],niters[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
