// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// estimate_par_c_DeepState_TestHarness_generation.cpp and estimate_par_c_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector estimate_par_c(NumericVector X, double rho_max);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector X  = RcppDeepState_NumericVector();
  qs::c_qsave(X,"/home/akhila/fuzzer_packages/fuzzedpackages/partialAR/inst/testfiles/estimate_par_c/inputs/X.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "X values: "<< X << std::endl;
  NumericVector rho_max(1);
  rho_max[0]  = RcppDeepState_double();
  qs::c_qsave(rho_max,"/home/akhila/fuzzer_packages/fuzzedpackages/partialAR/inst/testfiles/estimate_par_c/inputs/rho_max.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rho_max values: "<< rho_max << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    estimate_par_c(X,rho_max[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
