// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// coordonneesGrappe_DeepState_TestHarness_generation.cpp and coordonneesGrappe_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

std::vector<int> coordonneesGrappe(int iNiveauMax, int iNoGrappe);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector iNiveauMax(1);
  iNiveauMax[0]  = RcppDeepState_int();
  std::string iNiveauMax_t = "/home/akhila/fuzzer_packages/fuzzedpackages/btb/inst/testfiles/coordonneesGrappe/libFuzzer_coordonneesGrappe/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_iNiveauMax.qs";
  qs::c_qsave(iNiveauMax,iNiveauMax_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "iNiveauMax values: "<< iNiveauMax << std::endl;
  IntegerVector iNoGrappe(1);
  iNoGrappe[0]  = RcppDeepState_int();
  std::string iNoGrappe_t = "/home/akhila/fuzzer_packages/fuzzedpackages/btb/inst/testfiles/coordonneesGrappe/libFuzzer_coordonneesGrappe/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_iNoGrappe.qs";
  qs::c_qsave(iNoGrappe,iNoGrappe_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "iNoGrappe values: "<< iNoGrappe << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    coordonneesGrappe(iNiveauMax[0],iNoGrappe[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
