// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// create_prc_curve_DeepState_TestHarness_generation.cpp and create_prc_curve_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::List create_prc_curve(const Rcpp::NumericVector& tps, const Rcpp::NumericVector& fps, const Rcpp::NumericVector& sn, const Rcpp::NumericVector& pr, double x_bins);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector tps  = RcppDeepState_NumericVector();
  std::string tps_t = "/home/akhila/fuzzer_packages/fuzzedpackages/precrec/inst/testfiles/create_prc_curve/libFuzzer_create_prc_curve/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_tps.qs";
  qs::c_qsave(tps,tps_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tps values: "<< tps << std::endl;
  NumericVector fps  = RcppDeepState_NumericVector();
  std::string fps_t = "/home/akhila/fuzzer_packages/fuzzedpackages/precrec/inst/testfiles/create_prc_curve/libFuzzer_create_prc_curve/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_fps.qs";
  qs::c_qsave(fps,fps_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "fps values: "<< fps << std::endl;
  NumericVector sn  = RcppDeepState_NumericVector();
  std::string sn_t = "/home/akhila/fuzzer_packages/fuzzedpackages/precrec/inst/testfiles/create_prc_curve/libFuzzer_create_prc_curve/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_sn.qs";
  qs::c_qsave(sn,sn_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "sn values: "<< sn << std::endl;
  NumericVector pr  = RcppDeepState_NumericVector();
  std::string pr_t = "/home/akhila/fuzzer_packages/fuzzedpackages/precrec/inst/testfiles/create_prc_curve/libFuzzer_create_prc_curve/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_pr.qs";
  qs::c_qsave(pr,pr_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "pr values: "<< pr << std::endl;
  NumericVector x_bins(1);
  x_bins[0]  = RcppDeepState_double();
  std::string x_bins_t = "/home/akhila/fuzzer_packages/fuzzedpackages/precrec/inst/testfiles/create_prc_curve/libFuzzer_create_prc_curve/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_x_bins.qs";
  qs::c_qsave(x_bins,x_bins_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x_bins values: "<< x_bins << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    create_prc_curve(tps,fps,sn,pr,x_bins[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
