// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// metaphone_internal_DeepState_TestHarness_generation.cpp and metaphone_internal_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::CharacterVector metaphone_internal(Rcpp::CharacterVector word, int maxCodeLen);

TEST(,){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  CharacterVector word  = RcppDeepState_CharacterVector();
  std::string word_t = "/home/akhila/fuzzer_packages/fuzzedpackages/phonics/inst/testfiles/metaphone_internal/AFL_metaphone_internal/afl_inputs/" + std::to_string(t) + "_word.qs";
  qs::c_qsave(word,word_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "word values: "<< word << std::endl;
  IntegerVector maxCodeLen(1);
  maxCodeLen[0]  = RcppDeepState_int();
  std::string maxCodeLen_t = "/home/akhila/fuzzer_packages/fuzzedpackages/phonics/inst/testfiles/metaphone_internal/AFL_metaphone_internal/afl_inputs/" + std::to_string(t) + "_maxCodeLen.qs";
  qs::c_qsave(maxCodeLen,maxCodeLen_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "maxCodeLen values: "<< maxCodeLen << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    metaphone_internal(word,maxCodeLen[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
