// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// clusterStat_DeepState_TestHarness_generation.cpp and clusterStat_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List clusterStat(NumericVector trueGroup, NumericVector group);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector trueGroup  = RcppDeepState_NumericVector();
  qs::c_qsave(trueGroup,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/clusterStat/inputs/trueGroup.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "trueGroup values: "<< trueGroup << std::endl;
  NumericVector group  = RcppDeepState_NumericVector();
  qs::c_qsave(group,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/clusterStat/inputs/group.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "group values: "<< group << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    clusterStat(trueGroup,group);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
