// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// test_CheckSmallIntervals_DeepState_TestHarness_generation.cpp and test_CheckSmallIntervals_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector test_CheckSmallIntervals(const NumericVector& x, const double& p, const int& dn);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector x  = RcppDeepState_NumericVector();
  qs::c_qsave(x,"/home/akhila/fuzzer_packages/fuzzedpackages/pvar/inst/testfiles/test_CheckSmallIntervals/inputs/x.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "x values: "<< x << std::endl;
  NumericVector p(1);
  p[0]  = RcppDeepState_double();
  qs::c_qsave(p,"/home/akhila/fuzzer_packages/fuzzedpackages/pvar/inst/testfiles/test_CheckSmallIntervals/inputs/p.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "p values: "<< p << std::endl;
  IntegerVector dn(1);
  dn[0]  = RcppDeepState_int();
  qs::c_qsave(dn,"/home/akhila/fuzzer_packages/fuzzedpackages/pvar/inst/testfiles/test_CheckSmallIntervals/inputs/dn.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "dn values: "<< dn << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    test_CheckSmallIntervals(x,p[0],dn[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
