// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// refinedSoundex_internal_DeepState_TestHarness_generation.cpp and refinedSoundex_internal_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::CharacterVector refinedSoundex_internal(Rcpp::CharacterVector word, int maxCodeLen);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  CharacterVector word  = RcppDeepState_CharacterVector();
  qs::c_qsave(word,"/home/akhila/fuzzer_packages/fuzzedpackages/phonics/inst/testfiles/refinedSoundex_internal/inputs/word.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "word values: "<< word << std::endl;
  IntegerVector maxCodeLen(1);
  maxCodeLen[0]  = RcppDeepState_int();
  qs::c_qsave(maxCodeLen,"/home/akhila/fuzzer_packages/fuzzedpackages/phonics/inst/testfiles/refinedSoundex_internal/inputs/maxCodeLen.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "maxCodeLen values: "<< maxCodeLen << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    refinedSoundex_internal(word,maxCodeLen[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
