// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// eigendec_DeepState_TestHarness_generation.cpp and eigendec_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List eigendec(arma::mat M);

TEST(,){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  std::ofstream M_stream;
  arma::mat M  = RcppDeepState_mat();
  M_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/gasper/inst/testfiles/eigendec/inputs/M");
  M_stream << M;
  std::cout << "M values: "<< M << std::endl;
  M_stream.close();
  std::cout << "input ends" << std::endl;
  try{
    eigendec(M);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
