// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// get_codes_DeepState_TestHarness_generation.cpp and get_codes_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::List get_codes(int icdv);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector icdv(1);
  icdv[0]  = RcppDeepState_int();
  qs::c_qsave(icdv,"/home/akhila/fuzzer_packages/fuzzedpackages/pccc/inst/testfiles/get_codes/inputs/icdv.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "icdv values: "<< icdv << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    get_codes(icdv[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
