# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Chaotic <- function(n, q, v0, z0) {
    .Call(`_qGaussian_Chaotic`, n, q, v0, z0)
}

