// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// stopping_criteria_DeepState_TestHarness_generation.cpp and stopping_criteria_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

int stopping_criteria(NumericMatrix mu, NumericMatrix mu1, int ndim, int numbers, int count, double epsilon);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix mu  = RcppDeepState_NumericMatrix();
  qs::c_qsave(mu,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/stopping_criteria/inputs/mu.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mu values: "<< mu << std::endl;
  NumericMatrix mu1  = RcppDeepState_NumericMatrix();
  qs::c_qsave(mu1,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/stopping_criteria/inputs/mu1.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mu1 values: "<< mu1 << std::endl;
  IntegerVector ndim(1);
  ndim[0]  = RcppDeepState_int();
  qs::c_qsave(ndim,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/stopping_criteria/inputs/ndim.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ndim values: "<< ndim << std::endl;
  IntegerVector numbers(1);
  numbers[0]  = RcppDeepState_int();
  qs::c_qsave(numbers,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/stopping_criteria/inputs/numbers.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "numbers values: "<< numbers << std::endl;
  IntegerVector count(1);
  count[0]  = RcppDeepState_int();
  qs::c_qsave(count,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/stopping_criteria/inputs/count.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "count values: "<< count << std::endl;
  NumericVector epsilon(1);
  epsilon[0]  = RcppDeepState_double();
  qs::c_qsave(epsilon,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/stopping_criteria/inputs/epsilon.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "epsilon values: "<< epsilon << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    stopping_criteria(mu,mu1,ndim[0],numbers[0],count[0],epsilon[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
