// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// PRclustADMM_DeepState_TestHarness_generation.cpp and PRclustADMM_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List PRclustADMM(NumericMatrix data, double rho, double lambda2, double tau, int mumethod, int methods, double epsilon);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix data  = RcppDeepState_NumericMatrix();
  qs::c_qsave(data,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/PRclustADMM/inputs/data.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "data values: "<< data << std::endl;
  NumericVector rho(1);
  rho[0]  = RcppDeepState_double();
  qs::c_qsave(rho,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/PRclustADMM/inputs/rho.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rho values: "<< rho << std::endl;
  NumericVector lambda2(1);
  lambda2[0]  = RcppDeepState_double();
  qs::c_qsave(lambda2,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/PRclustADMM/inputs/lambda2.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "lambda2 values: "<< lambda2 << std::endl;
  NumericVector tau(1);
  tau[0]  = RcppDeepState_double();
  qs::c_qsave(tau,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/PRclustADMM/inputs/tau.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tau values: "<< tau << std::endl;
  IntegerVector mumethod(1);
  mumethod[0]  = RcppDeepState_int();
  qs::c_qsave(mumethod,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/PRclustADMM/inputs/mumethod.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mumethod values: "<< mumethod << std::endl;
  IntegerVector methods(1);
  methods[0]  = RcppDeepState_int();
  qs::c_qsave(methods,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/PRclustADMM/inputs/methods.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "methods values: "<< methods << std::endl;
  NumericVector epsilon(1);
  epsilon[0]  = RcppDeepState_double();
  qs::c_qsave(epsilon,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/PRclustADMM/inputs/epsilon.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "epsilon values: "<< epsilon << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    PRclustADMM(data,rho[0],lambda2[0],tau[0],mumethod[0],methods[0],epsilon[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
