// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// is_zero_theta_DeepState_TestHarness_generation.cpp and is_zero_theta_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

int is_zero_theta(NumericMatrix theta, int j, int ndim);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix theta  = RcppDeepState_NumericMatrix();
  std::string theta_t = "/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/is_zero_theta/libFuzzer_is_zero_theta/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_theta.qs";
  qs::c_qsave(theta,theta_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "theta values: "<< theta << std::endl;
  IntegerVector j(1);
  j[0]  = RcppDeepState_int();
  std::string j_t = "/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/is_zero_theta/libFuzzer_is_zero_theta/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_j.qs";
  qs::c_qsave(j,j_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "j values: "<< j << std::endl;
  IntegerVector ndim(1);
  ndim[0]  = RcppDeepState_int();
  std::string ndim_t = "/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/is_zero_theta/libFuzzer_is_zero_theta/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_ndim.qs";
  qs::c_qsave(ndim,ndim_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ndim values: "<< ndim << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    is_zero_theta(theta,j[0],ndim[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
