// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// ridgePgen_DeepState_TestHarness_generation.cpp and ridgePgen_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::mat ridgePgen(const arma::mat& S, const arma::mat& lambda, const arma::mat& target, const int& nInit, const double& minSuccDiff);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  std::ofstream S_stream;
  arma::mat S  = RcppDeepState_mat();
  S_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/porridge/inst/testfiles/ridgePgen/inputs/S");
  S_stream << S;
  std::cout << "S values: "<< S << std::endl;
  S_stream.close();
  std::ofstream lambda_stream;
  arma::mat lambda  = RcppDeepState_mat();
  lambda_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/porridge/inst/testfiles/ridgePgen/inputs/lambda");
  lambda_stream << lambda;
  std::cout << "lambda values: "<< lambda << std::endl;
  lambda_stream.close();
  std::ofstream target_stream;
  arma::mat target  = RcppDeepState_mat();
  target_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/porridge/inst/testfiles/ridgePgen/inputs/target");
  target_stream << target;
  std::cout << "target values: "<< target << std::endl;
  target_stream.close();
  IntegerVector nInit(1);
  nInit[0]  = RcppDeepState_int();
  std::string nInit_t = "/home/akhila/fuzzer_packages/fuzzedpackages/porridge/inst/testfiles/ridgePgen/libFuzzer_ridgePgen/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_nInit.qs";
  qs::c_qsave(nInit,nInit_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nInit values: "<< nInit << std::endl;
  NumericVector minSuccDiff(1);
  minSuccDiff[0]  = RcppDeepState_double();
  std::string minSuccDiff_t = "/home/akhila/fuzzer_packages/fuzzedpackages/porridge/inst/testfiles/ridgePgen/libFuzzer_ridgePgen/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_minSuccDiff.qs";
  qs::c_qsave(minSuccDiff,minSuccDiff_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "minSuccDiff values: "<< minSuccDiff << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    ridgePgen(S,lambda,target,nInit[0],minSuccDiff[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
