// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// coeff_theta_DeepState_TestHarness_generation.cpp and coeff_theta_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector coeff_theta(const NumericMatrix& degree, const NumericVector& f, const NumericVector& normalized_const, const NumericVector& m_t, const int length_theta);

TEST(,){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix degree  = RcppDeepState_NumericMatrix();
  std::string degree_t = "/home/akhila/fuzzer_packages/fuzzedpackages/PAFit/inst/testfiles/coeff_theta/AFL_coeff_theta/afl_inputs/" + std::to_string(t) + "_degree.qs";
  qs::c_qsave(degree,degree_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "degree values: "<< degree << std::endl;
  NumericVector f  = RcppDeepState_NumericVector();
  std::string f_t = "/home/akhila/fuzzer_packages/fuzzedpackages/PAFit/inst/testfiles/coeff_theta/AFL_coeff_theta/afl_inputs/" + std::to_string(t) + "_f.qs";
  qs::c_qsave(f,f_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "f values: "<< f << std::endl;
  NumericVector normalized_  = RcppDeepState_NumericVector();
  std::string normalized_const_t = "/home/akhila/fuzzer_packages/fuzzedpackages/PAFit/inst/testfiles/coeff_theta/AFL_coeff_theta/afl_inputs/" + std::to_string(t) + "_normalized_const.qs";
  qs::c_qsave(normalized_const,normalized_const_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "normalized_const values: "<< normalized_const << std::endl;
  NumericVector m_t  = RcppDeepState_NumericVector();
  std::string m_t_t = "/home/akhila/fuzzer_packages/fuzzedpackages/PAFit/inst/testfiles/coeff_theta/AFL_coeff_theta/afl_inputs/" + std::to_string(t) + "_m_t.qs";
  qs::c_qsave(m_t,m_t_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "m_t values: "<< m_t << std::endl;
  IntegerVector length_theta(1);
  length_theta[0]  = RcppDeepState_int();
  std::string length_theta_t = "/home/akhila/fuzzer_packages/fuzzedpackages/PAFit/inst/testfiles/coeff_theta/AFL_coeff_theta/afl_inputs/" + std::to_string(t) + "_length_theta.qs";
  qs::c_qsave(length_theta,length_theta_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "length_theta values: "<< length_theta << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    coeff_theta(degree,f,normalized_const,m_t,length_theta[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
