// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// kalman_gain_par_mr_DeepState_TestHarness_generation.cpp and kalman_gain_par_mr_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double kalman_gain_par_mr(double rho, double sigma_M, double sigma_R);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector rho(1);
  rho[0]  = RcppDeepState_double();
  qs::c_qsave(rho,"/home/akhila/fuzzer_packages/fuzzedpackages/partialCI/inst/testfiles/kalman_gain_par_mr/inputs/rho.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rho values: "<< rho << std::endl;
  NumericVector sigma_M(1);
  sigma_M[0]  = RcppDeepState_double();
  qs::c_qsave(sigma_M,"/home/akhila/fuzzer_packages/fuzzedpackages/partialCI/inst/testfiles/kalman_gain_par_mr/inputs/sigma_M.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "sigma_M values: "<< sigma_M << std::endl;
  NumericVector sigma_R(1);
  sigma_R[0]  = RcppDeepState_double();
  qs::c_qsave(sigma_R,"/home/akhila/fuzzer_packages/fuzzedpackages/partialCI/inst/testfiles/kalman_gain_par_mr/inputs/sigma_R.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "sigma_R values: "<< sigma_R << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    kalman_gain_par_mr(rho[0],sigma_M[0],sigma_R[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
