// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// pres_atm_kPa_DeepState_TestHarness_generation.cpp and pres_atm_kPa_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector pres_atm_kPa(NumericVector altitude_m);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericVector altitude_m  = RcppDeepState_NumericVector();
  std::string altitude_m_t = "/home/akhila/fuzzer_packages/fuzzedpackages/physiology/inst/testfiles/pres_atm_kPa/libFuzzer_pres_atm_kPa/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_altitude_m.qs";
  qs::c_qsave(altitude_m,altitude_m_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "altitude_m values: "<< altitude_m << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    pres_atm_kPa(altitude_m);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
