// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// tree_search_rcpp_predict_DeepState_TestHarness_generation.cpp and tree_search_rcpp_predict_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::NumericVector tree_search_rcpp_predict(const Rcpp::NumericMatrix& tree_array, const Rcpp::NumericMatrix& X);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix tree_array  = RcppDeepState_NumericMatrix();
  std::string tree_array_t = "/home/akhila/fuzzer_packages/fuzzedpackages/policytree/inst/testfiles/tree_search_rcpp_predict/libFuzzer_tree_search_rcpp_predict/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_tree_array.qs";
  qs::c_qsave(tree_array,tree_array_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tree_array values: "<< tree_array << std::endl;
  NumericMatrix X  = RcppDeepState_NumericMatrix();
  std::string X_t = "/home/akhila/fuzzer_packages/fuzzedpackages/policytree/inst/testfiles/tree_search_rcpp_predict/libFuzzer_tree_search_rcpp_predict/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_X.qs";
  qs::c_qsave(X,X_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "X values: "<< X << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    tree_search_rcpp_predict(tree_array,X);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
