// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// BestGenos_DeepState_TestHarness_generation.cpp and BestGenos_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerMatrix BestGenos(NumericVector probs, int ploidy, int ntaxa, int nalleles);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector probs  = RcppDeepState_NumericVector();
  qs::c_qsave(probs,"/home/akhila/fuzzer_packages/fuzzedpackages/polyRAD/inst/testfiles/BestGenos/inputs/probs.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "probs values: "<< probs << std::endl;
  IntegerVector ploidy(1);
  ploidy[0]  = RcppDeepState_int();
  qs::c_qsave(ploidy,"/home/akhila/fuzzer_packages/fuzzedpackages/polyRAD/inst/testfiles/BestGenos/inputs/ploidy.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ploidy values: "<< ploidy << std::endl;
  IntegerVector ntaxa(1);
  ntaxa[0]  = RcppDeepState_int();
  qs::c_qsave(ntaxa,"/home/akhila/fuzzer_packages/fuzzedpackages/polyRAD/inst/testfiles/BestGenos/inputs/ntaxa.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ntaxa values: "<< ntaxa << std::endl;
  IntegerVector nalleles(1);
  nalleles[0]  = RcppDeepState_int();
  qs::c_qsave(nalleles,"/home/akhila/fuzzer_packages/fuzzedpackages/polyRAD/inst/testfiles/BestGenos/inputs/nalleles.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "nalleles values: "<< nalleles << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    BestGenos(probs,ploidy[0],ntaxa[0],nalleles[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
