// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// computePolyTerms_DeepState_TestHarness_generation.cpp and computePolyTerms_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List computePolyTerms(int degree, int k_expand, int k_lin);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector degree(1);
  degree[0]  = RcppDeepState_int();
  qs::c_qsave(degree,"/home/akhila/fuzzer_packages/fuzzedpackages/polywog/inst/testfiles/computePolyTerms/inputs/degree.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "degree values: "<< degree << std::endl;
  IntegerVector k_expand(1);
  k_expand[0]  = RcppDeepState_int();
  qs::c_qsave(k_expand,"/home/akhila/fuzzer_packages/fuzzedpackages/polywog/inst/testfiles/computePolyTerms/inputs/k_expand.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "k_expand values: "<< k_expand << std::endl;
  IntegerVector k_lin(1);
  k_lin[0]  = RcppDeepState_int();
  qs::c_qsave(k_lin,"/home/akhila/fuzzer_packages/fuzzedpackages/polywog/inst/testfiles/computePolyTerms/inputs/k_lin.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "k_lin values: "<< k_lin << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    computePolyTerms(degree[0],k_expand[0],k_lin[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
