// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// buffer_keep_DeepState_TestHarness_generation.cpp and buffer_keep_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

LogicalMatrix buffer_keep(const NumericMatrix& points, const NumericMatrix& lims, const double& R);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix points  = RcppDeepState_NumericMatrix();
  std::string points_t = "/home/akhila/fuzzer_packages/fuzzedpackages/palm/inst/testfiles/buffer_keep/libFuzzer_buffer_keep/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_points.qs";
  qs::c_qsave(points,points_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "points values: "<< points << std::endl;
  NumericMatrix lims  = RcppDeepState_NumericMatrix();
  std::string lims_t = "/home/akhila/fuzzer_packages/fuzzedpackages/palm/inst/testfiles/buffer_keep/libFuzzer_buffer_keep/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_lims.qs";
  qs::c_qsave(lims,lims_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "lims values: "<< lims << std::endl;
  NumericVector R(1);
  R[0]  = RcppDeepState_double();
  std::string R_t = "/home/akhila/fuzzer_packages/fuzzedpackages/palm/inst/testfiles/buffer_keep/libFuzzer_buffer_keep/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_R.qs";
  qs::c_qsave(R,R_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "R values: "<< R << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    buffer_keep(points,lims,R[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
