// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// constituerMatriceEffectifs_DeepState_TestHarness_generation.cpp and constituerMatriceEffectifs_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::Mat<int> constituerMatriceEffectifs(IntegerVector vLigneObservation, IntegerVector vColonneObservation);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector vLigneObservation  = RcppDeepState_IntegerVector();
  qs::c_qsave(vLigneObservation,"/home/akhila/fuzzer_packages/fuzzedpackages/btb/inst/testfiles/constituerMatriceEffectifs/inputs/vLigneObservation.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "vLigneObservation values: "<< vLigneObservation << std::endl;
  IntegerVector vColonneObservation  = RcppDeepState_IntegerVector();
  qs::c_qsave(vColonneObservation,"/home/akhila/fuzzer_packages/fuzzedpackages/btb/inst/testfiles/constituerMatriceEffectifs/inputs/vColonneObservation.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "vColonneObservation values: "<< vColonneObservation << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    constituerMatriceEffectifs(vLigneObservation,vColonneObservation);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
