// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// PRclustADMM_DeepState_TestHarness_generation.cpp and PRclustADMM_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List PRclustADMM(NumericMatrix data, double rho, double lambda2, double tau, int mumethod, int methods, double epsilon);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix data  = RcppDeepState_NumericMatrix();
  std::string data_t = "/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/PRclustADMM/libFuzzer_PRclustADMM/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_data.qs";
  qs::c_qsave(data,data_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "data values: "<< data << std::endl;
  NumericVector rho(1);
  rho[0]  = RcppDeepState_double();
  std::string rho_t = "/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/PRclustADMM/libFuzzer_PRclustADMM/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_rho.qs";
  qs::c_qsave(rho,rho_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "rho values: "<< rho << std::endl;
  NumericVector lambda2(1);
  lambda2[0]  = RcppDeepState_double();
  std::string lambda2_t = "/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/PRclustADMM/libFuzzer_PRclustADMM/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_lambda2.qs";
  qs::c_qsave(lambda2,lambda2_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "lambda2 values: "<< lambda2 << std::endl;
  NumericVector tau(1);
  tau[0]  = RcppDeepState_double();
  std::string tau_t = "/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/PRclustADMM/libFuzzer_PRclustADMM/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_tau.qs";
  qs::c_qsave(tau,tau_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tau values: "<< tau << std::endl;
  IntegerVector mumethod(1);
  mumethod[0]  = RcppDeepState_int();
  std::string mumethod_t = "/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/PRclustADMM/libFuzzer_PRclustADMM/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_mumethod.qs";
  qs::c_qsave(mumethod,mumethod_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mumethod values: "<< mumethod << std::endl;
  IntegerVector methods(1);
  methods[0]  = RcppDeepState_int();
  std::string methods_t = "/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/PRclustADMM/libFuzzer_PRclustADMM/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_methods.qs";
  qs::c_qsave(methods,methods_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "methods values: "<< methods << std::endl;
  NumericVector epsilon(1);
  epsilon[0]  = RcppDeepState_double();
  std::string epsilon_t = "/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/PRclustADMM/libFuzzer_PRclustADMM/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_epsilon.qs";
  qs::c_qsave(epsilon,epsilon_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "epsilon values: "<< epsilon << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    PRclustADMM(data,rho[0],lambda2[0],tau[0],mumethod[0],methods[0],epsilon[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
