// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// qatd_cpp_is_grouped_numeric_DeepState_TestHarness_generation.cpp and qatd_cpp_is_grouped_numeric_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

bool qatd_cpp_is_grouped_numeric(NumericVector values_, IntegerVector groups_);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector values_  = RcppDeepState_NumericVector();
  qs::c_qsave(values_,"/home/akhila/fuzzer_packages/fuzzedpackages/quanteda/inst/testfiles/qatd_cpp_is_grouped_numeric/inputs/values_.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "values_ values: "<< values_ << std::endl;
  IntegerVector groups_  = RcppDeepState_IntegerVector();
  qs::c_qsave(groups_,"/home/akhila/fuzzer_packages/fuzzedpackages/quanteda/inst/testfiles/qatd_cpp_is_grouped_numeric/inputs/groups_.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "groups_ values: "<< groups_ << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    qatd_cpp_is_grouped_numeric(values_,groups_);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
