// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// getGrid_DeepState_TestHarness_generation.cpp and getGrid_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::NumericVector getGrid(Rcpp::IntegerVector U, Rcpp::NumericVector ftgrid);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector U  = RcppDeepState_IntegerVector();
  qs::c_qsave(U,"/home/akhila/fuzzer_packages/fuzzedpackages/peppm/inst/testfiles/getGrid/inputs/U.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "U values: "<< U << std::endl;
  NumericVector ftgrid  = RcppDeepState_NumericVector();
  qs::c_qsave(ftgrid,"/home/akhila/fuzzer_packages/fuzzedpackages/peppm/inst/testfiles/getGrid/inputs/ftgrid.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ftgrid values: "<< ftgrid << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    getGrid(U,ftgrid);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
