// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// BestPloidies_DeepState_TestHarness_generation.cpp and BestPloidies_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerVector BestPloidies(NumericMatrix chisq);

TEST(,){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix chisq  = RcppDeepState_NumericMatrix();
  std::string chisq_t = "/home/akhila/fuzzer_packages/fuzzedpackages/polyRAD/inst/testfiles/BestPloidies/AFL_BestPloidies/afl_inputs/" + std::to_string(t) + "_chisq.qs";
  qs::c_qsave(chisq,chisq_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "chisq values: "<< chisq << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    BestPloidies(chisq);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
