// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// GENLIST_DeepState_TestHarness_generation.cpp and GENLIST_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerMatrix GENLIST(int ng, int na1, int m2);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector ng(1);
  ng[0]  = RcppDeepState_int();
  qs::c_qsave(ng,"/home/akhila/fuzzer_packages/fuzzedpackages/polysat/inst/testfiles/GENLIST/inputs/ng.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ng values: "<< ng << std::endl;
  IntegerVector na1(1);
  na1[0]  = RcppDeepState_int();
  qs::c_qsave(na1,"/home/akhila/fuzzer_packages/fuzzedpackages/polysat/inst/testfiles/GENLIST/inputs/na1.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "na1 values: "<< na1 << std::endl;
  IntegerVector m2(1);
  m2[0]  = RcppDeepState_int();
  qs::c_qsave(m2,"/home/akhila/fuzzer_packages/fuzzedpackages/polysat/inst/testfiles/GENLIST/inputs/m2.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "m2 values: "<< m2 << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    GENLIST(ng[0],na1[0],m2[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
