// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// residual_mu_DeepState_TestHarness_generation.cpp and residual_mu_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double residual_mu(NumericMatrix mu1, NumericMatrix mu, int ndim, int numbers);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix mu1  = RcppDeepState_NumericMatrix();
  std::string mu1_t = "/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/residual_mu/libFuzzer_residual_mu/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_mu1.qs";
  std::string mu_t = "/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/residual_mu/libFuzzer_residual_mu/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_mu.qs";
  qs::c_qsave(mu1,mu1_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mu1 values: "<< mu1 << std::endl;
  NumericMatrix mu  = RcppDeepState_NumericMatrix();
  std::string mu_t = "/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/residual_mu/libFuzzer_residual_mu/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_mu.qs";
  qs::c_qsave(mu,mu_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mu values: "<< mu << std::endl;
  IntegerVector ndim(1);
  ndim[0]  = RcppDeepState_int();
  std::string ndim_t = "/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/residual_mu/libFuzzer_residual_mu/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_ndim.qs";
  qs::c_qsave(ndim,ndim_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ndim values: "<< ndim << std::endl;
  IntegerVector numbers(1);
  numbers[0]  = RcppDeepState_int();
  std::string numbers_t = "/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/residual_mu/libFuzzer_residual_mu/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_numbers.qs";
  qs::c_qsave(numbers,numbers_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "numbers values: "<< numbers << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    residual_mu(mu1,mu,ndim[0],numbers[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
