// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// lower_bound___DeepState_TestHarness_generation.cpp and lower_bound___DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerVector lower_bound__(const NumericVector xq, const NumericVector xvec);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector xq  = RcppDeepState_NumericVector();
  qs::c_qsave(xq,"/home/akhila/fuzzer_packages/fuzzedpackages/protViz/inst/testfiles/lower_bound__/inputs/xq.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "xq values: "<< xq << std::endl;
  NumericVector xvec  = RcppDeepState_NumericVector();
  qs::c_qsave(xvec,"/home/akhila/fuzzer_packages/fuzzedpackages/protViz/inst/testfiles/lower_bound__/inputs/xvec.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "xvec values: "<< xvec << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    lower_bound__(xq,xvec);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
