// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// generateCompositions_DeepState_TestHarness_generation.cpp and generateCompositions_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List generateCompositions(int numContributors);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector numContributors(1);
  numContributors[0]  = RcppDeepState_int();
  qs::c_qsave(numContributors,"/home/akhila/fuzzer_packages/fuzzedpackages/DNAtools/inst/testfiles/generateCompositions/inputs/numContributors.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "numContributors values: "<< numContributors << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    generateCompositions(numContributors[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
