// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// getGrid_DeepState_TestHarness_generation.cpp and getGrid_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::NumericVector getGrid(Rcpp::IntegerVector U, Rcpp::NumericVector ftgrid);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  IntegerVector U  = RcppDeepState_IntegerVector();
  std::string U_t = "/home/akhila/fuzzer_packages/fuzzedpackages/peppm/inst/testfiles/getGrid/libFuzzer_getGrid/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_U.qs";
  qs::c_qsave(U,U_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "U values: "<< U << std::endl;
  NumericVector ftgrid  = RcppDeepState_NumericVector();
  std::string ftgrid_t = "/home/akhila/fuzzer_packages/fuzzedpackages/peppm/inst/testfiles/getGrid/libFuzzer_getGrid/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_ftgrid.qs";
  qs::c_qsave(ftgrid,ftgrid_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ftgrid values: "<< ftgrid << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    getGrid(U,ftgrid);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
