// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// distance_umu_DeepState_TestHarness_generation.cpp and distance_umu_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

double distance_umu(NumericMatrix u, NumericMatrix data, int ndim, int i, int j, int uj);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix u  = RcppDeepState_NumericMatrix();
  std::string u_t = "/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/distance_umu/libFuzzer_distance_umu/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_u.qs";
  qs::c_qsave(u,u_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "u values: "<< u << std::endl;
  NumericMatrix data  = RcppDeepState_NumericMatrix();
  std::string data_t = "/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/distance_umu/libFuzzer_distance_umu/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_data.qs";
  qs::c_qsave(data,data_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "data values: "<< data << std::endl;
  IntegerVector ndim(1);
  ndim[0]  = RcppDeepState_int();
  std::string ndim_t = "/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/distance_umu/libFuzzer_distance_umu/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_ndim.qs";
  qs::c_qsave(ndim,ndim_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ndim values: "<< ndim << std::endl;
  IntegerVector i(1);
  i[0]  = RcppDeepState_int();
  std::string i_t = "/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/distance_umu/libFuzzer_distance_umu/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_i.qs";
  qs::c_qsave(i,i_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "i values: "<< i << std::endl;
  IntegerVector j(1);
  j[0]  = RcppDeepState_int();
  std::string j_t = "/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/distance_umu/libFuzzer_distance_umu/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_j.qs";
  qs::c_qsave(j,j_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "j values: "<< j << std::endl;
  IntegerVector uj(1);
  uj[0]  = RcppDeepState_int();
  std::string u_t = "/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/distance_umu/libFuzzer_distance_umu/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_u.qs";
  std::string uj_t = "/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/distance_umu/libFuzzer_distance_umu/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_uj.qs";
  qs::c_qsave(uj,uj_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "uj values: "<< uj << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    distance_umu(u,data,ndim[0],i[0],j[0],uj[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
