// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// judge_iteration_DeepState_TestHarness_generation.cpp and judge_iteration_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

int judge_iteration(NumericMatrix data, NumericMatrix mu, NumericMatrix theta, NumericMatrix mu1, NumericMatrix theta1, double lambda1, double lambda2, double tau, int ndim, int numbers, int count, int methods);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix data  = RcppDeepState_NumericMatrix();
  qs::c_qsave(data,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/judge_iteration/inputs/data.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "data values: "<< data << std::endl;
  NumericMatrix mu  = RcppDeepState_NumericMatrix();
  qs::c_qsave(mu,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/judge_iteration/inputs/mu.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mu values: "<< mu << std::endl;
  NumericMatrix theta  = RcppDeepState_NumericMatrix();
  qs::c_qsave(theta,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/judge_iteration/inputs/theta.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "theta values: "<< theta << std::endl;
  NumericMatrix mu1  = RcppDeepState_NumericMatrix();
  qs::c_qsave(mu1,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/judge_iteration/inputs/mu1.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mu1 values: "<< mu1 << std::endl;
  NumericMatrix theta1  = RcppDeepState_NumericMatrix();
  qs::c_qsave(theta1,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/judge_iteration/inputs/theta1.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "theta1 values: "<< theta1 << std::endl;
  NumericVector lambda1(1);
  lambda1[0]  = RcppDeepState_double();
  qs::c_qsave(lambda1,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/judge_iteration/inputs/lambda1.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "lambda1 values: "<< lambda1 << std::endl;
  NumericVector lambda2(1);
  lambda2[0]  = RcppDeepState_double();
  qs::c_qsave(lambda2,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/judge_iteration/inputs/lambda2.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "lambda2 values: "<< lambda2 << std::endl;
  NumericVector tau(1);
  tau[0]  = RcppDeepState_double();
  qs::c_qsave(tau,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/judge_iteration/inputs/tau.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tau values: "<< tau << std::endl;
  IntegerVector ndim(1);
  ndim[0]  = RcppDeepState_int();
  qs::c_qsave(ndim,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/judge_iteration/inputs/ndim.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "ndim values: "<< ndim << std::endl;
  IntegerVector numbers(1);
  numbers[0]  = RcppDeepState_int();
  qs::c_qsave(numbers,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/judge_iteration/inputs/numbers.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "numbers values: "<< numbers << std::endl;
  IntegerVector count(1);
  count[0]  = RcppDeepState_int();
  qs::c_qsave(count,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/judge_iteration/inputs/count.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "count values: "<< count << std::endl;
  IntegerVector methods(1);
  methods[0]  = RcppDeepState_int();
  qs::c_qsave(methods,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/judge_iteration/inputs/methods.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "methods values: "<< methods << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    judge_iteration(data,mu,theta,mu1,theta1,lambda1[0],lambda2[0],tau[0],ndim[0],numbers[0],count[0],methods[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
