// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// PRclustOriginal_DeepState_TestHarness_generation.cpp and PRclustOriginal_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

List PRclustOriginal(NumericMatrix data, double lambda1, double lambda2, double tau, int mumethod, int methods);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix data  = RcppDeepState_NumericMatrix();
  qs::c_qsave(data,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/PRclustOriginal/inputs/data.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "data values: "<< data << std::endl;
  NumericVector lambda1(1);
  lambda1[0]  = RcppDeepState_double();
  qs::c_qsave(lambda1,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/PRclustOriginal/inputs/lambda1.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "lambda1 values: "<< lambda1 << std::endl;
  NumericVector lambda2(1);
  lambda2[0]  = RcppDeepState_double();
  qs::c_qsave(lambda2,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/PRclustOriginal/inputs/lambda2.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "lambda2 values: "<< lambda2 << std::endl;
  NumericVector tau(1);
  tau[0]  = RcppDeepState_double();
  qs::c_qsave(tau,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/PRclustOriginal/inputs/tau.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "tau values: "<< tau << std::endl;
  IntegerVector mumethod(1);
  mumethod[0]  = RcppDeepState_int();
  qs::c_qsave(mumethod,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/PRclustOriginal/inputs/mumethod.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mumethod values: "<< mumethod << std::endl;
  IntegerVector methods(1);
  methods[0]  = RcppDeepState_int();
  qs::c_qsave(methods,"/home/akhila/fuzzer_packages/fuzzedpackages/prclust/inst/testfiles/PRclustOriginal/inputs/methods.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "methods values: "<< methods << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    PRclustOriginal(data,lambda1[0],lambda2[0],tau[0],mumethod[0],methods[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
