// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// rcpp_pgdraw_DeepState_TestHarness_generation.cpp and rcpp_pgdraw_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector rcpp_pgdraw(NumericVector b, NumericVector c);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector b  = RcppDeepState_NumericVector();
  qs::c_qsave(b,"/home/akhila/fuzzer_packages/fuzzedpackages/pgdraw/inst/testfiles/rcpp_pgdraw/inputs/b.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "b values: "<< b << std::endl;
  NumericVector c  = RcppDeepState_NumericVector();
  qs::c_qsave(c,"/home/akhila/fuzzer_packages/fuzzedpackages/pgdraw/inst/testfiles/rcpp_pgdraw/inputs/c.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "c values: "<< c << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    rcpp_pgdraw(b,c);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
