// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// assign_cluster_DeepState_TestHarness_generation.cpp and assign_cluster_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericVector assign_cluster(arma::mat& x, arma::mat init_centroids);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  std::ofstream x_stream;
  arma::mat x  = RcppDeepState_mat();
  x_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/partition/inst/testfiles/assign_cluster/inputs/x");
  x_stream << x;
  std::cout << "x values: "<< x << std::endl;
  x_stream.close();
  std::ofstream init_centroids_stream;
  arma::mat init_centroids  = RcppDeepState_mat();
  init_centroids_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/partition/inst/testfiles/assign_cluster/inputs/init_centroids");
  init_centroids_stream << init_centroids;
  std::cout << "init_centroids values: "<< init_centroids << std::endl;
  init_centroids_stream.close();
  std::cout << "input ends" << std::endl;
  try{
    assign_cluster(x,init_centroids);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
