// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fishercpp
NumericMatrix fishercpp(NumericMatrix& Xcpp, NumericVector& mucpp);
RcppExport SEXP _penMSM_fishercpp(SEXP XcppSEXP, SEXP mucppSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type Xcpp(XcppSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type mucpp(mucppSEXP);
    rcpp_result_gen = Rcpp::wrap(fishercpp(Xcpp, mucpp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_penMSM_fishercpp", (DL_FUNC) &_penMSM_fishercpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_penMSM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
