// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// fishercpp_DeepState_TestHarness_generation.cpp and fishercpp_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

NumericMatrix fishercpp(NumericMatrix& Xcpp, NumericVector& mucpp);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix Xcpp  = RcppDeepState_NumericMatrix();
  std::string Xcpp_t = "/home/akhila/fuzzer_packages/fuzzedpackages/penMSM/inst/testfiles/fishercpp/libFuzzer_fishercpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_Xcpp.qs";
  qs::c_qsave(Xcpp,Xcpp_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "Xcpp values: "<< Xcpp << std::endl;
  NumericVector mucpp  = RcppDeepState_NumericVector();
  std::string mucpp_t = "/home/akhila/fuzzer_packages/fuzzedpackages/penMSM/inst/testfiles/fishercpp/libFuzzer_fishercpp/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_mucpp.qs";
  qs::c_qsave(mucpp,mucpp_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "mucpp values: "<< mucpp << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    fishercpp(Xcpp,mucpp);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
