// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// hungariansafe_cc_DeepState_TestHarness_generation.cpp and hungariansafe_cc_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::imat hungariansafe_cc(Rcpp::NumericMatrix cost);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericMatrix cost  = RcppDeepState_NumericMatrix();
  qs::c_qsave(cost,"/home/akhila/fuzzer_packages/fuzzedpackages/geogrid/inst/testfiles/hungariansafe_cc/inputs/cost.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "cost values: "<< cost << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    hungariansafe_cc(cost);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
