// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// hungarian_cc_DeepState_TestHarness_generation.cpp and hungarian_cc_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::imat hungarian_cc(Rcpp::NumericMatrix cost);

TEST(,){
  static int rinside_flag = 0;
  if(rinside_flag == 0)
  {
    rinside_flag = 1;
    RInside R;
  } std::time_t current_timestamp = std::time(0);
  std::cout << "input starts" << std::endl;
  NumericMatrix cost  = RcppDeepState_NumericMatrix();
  std::string cost_t = "/home/akhila/fuzzer_packages/fuzzedpackages/geogrid/inst/testfiles/hungarian_cc/libFuzzer_hungarian_cc/libfuzzer_inputs/" + std::to_string(current_timestamp) +
          "_cost.qs";
  qs::c_qsave(cost,cost_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "cost values: "<< cost << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    hungarian_cc(cost);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
