// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// coprime_DeepState_TestHarness_generation.cpp and coprime_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

Rcpp::LogicalVector coprime(const Rcpp::IntegerVector& m, const Rcpp::IntegerVector& n);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  IntegerVector m  = RcppDeepState_IntegerVector();
  qs::c_qsave(m,"/home/akhila/fuzzer_packages/fuzzedpackages/primes/inst/testfiles/coprime/inputs/m.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "m values: "<< m << std::endl;
  IntegerVector n  = RcppDeepState_IntegerVector();
  qs::c_qsave(n,"/home/akhila/fuzzer_packages/fuzzedpackages/primes/inst/testfiles/coprime/inputs/n.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "n values: "<< n << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    coprime(m,n);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
