// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// RVcoeff_DeepState_TestHarness_generation.cpp and RVcoeff_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

arma::mat RVcoeff(arma::mat mDx, arma::mat mDy, arma::mat mC);

TEST(,){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  std::ofstream mDx_stream;
  arma::mat mDx  = RcppDeepState_mat();
  mDx_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/perfectphyloR/inst/testfiles/RVcoeff/inputs/mDx");
  mDx_stream << mDx;
  std::cout << "mDx values: "<< mDx << std::endl;
  mDx_stream.close();
  std::ofstream mDy_stream;
  arma::mat mDy  = RcppDeepState_mat();
  mDy_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/perfectphyloR/inst/testfiles/RVcoeff/inputs/mDy");
  mDy_stream << mDy;
  std::cout << "mDy values: "<< mDy << std::endl;
  mDy_stream.close();
  std::ofstream mC_stream;
  arma::mat mC  = RcppDeepState_mat();
  mC_stream.open("/home/akhila/fuzzer_packages/fuzzedpackages/perfectphyloR/inst/testfiles/RVcoeff/inputs/mC");
  mC_stream << mC;
  std::cout << "mC values: "<< mC << std::endl;
  mC_stream.close();
  std::cout << "input ends" << std::endl;
  try{
    RVcoeff(mDx,mDy,mC);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
