// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// nearbyPointsGreedyCluster_DeepState_TestHarness_generation.cpp and nearbyPointsGreedyCluster_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

IntegerVector nearbyPointsGreedyCluster(NumericVector p, double windowSize);

TEST(,){
  RInside R;
  std::cout << "input starts" << std::endl;
  NumericVector p  = RcppDeepState_NumericVector();
  qs::c_qsave(p,"/home/akhila/fuzzer_packages/fuzzedpackages/pagoda2/inst/testfiles/nearbyPointsGreedyCluster/inputs/p.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "p values: "<< p << std::endl;
  NumericVector windowSize(1);
  windowSize[0]  = RcppDeepState_double();
  qs::c_qsave(windowSize,"/home/akhila/fuzzer_packages/fuzzedpackages/pagoda2/inst/testfiles/nearbyPointsGreedyCluster/inputs/windowSize.qs",
		"high", "zstd", 1, 15, true, 1);
  std::cout << "windowSize values: "<< windowSize << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    nearbyPointsGreedyCluster(p,windowSize[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
