// AUTOMATICALLY GENERATED BY RCPPDEEPSTATE PLEASE DO NOT EDIT BY HAND, INSTEAD EDIT
// count_precedence_DeepState_TestHarness_generation.cpp and count_precedence_DeepState_TestHarness_checks.cpp

#include <fstream>
#include <ctime>
#include <RInside.h>
#include <iostream>
#include <RcppDeepState.h>
#include <qs.h>
#include <DeepState.hpp>

DataFrame count_precedence(CharacterVector cases, IntegerVector activities, int lead);

TEST(,){
  RInside R;
  std::time_t t = std::time(0);
  std::cout << "input starts" << std::endl;
  CharacterVector cases  = RcppDeepState_CharacterVector();
  std::string cases_t = "/home/akhila/fuzzer_packages/fuzzedpackages/processmapR/inst/testfiles/count_precedence/AFL_count_precedence/afl_inputs/" + std::to_string(t) + "_cases.qs";
  qs::c_qsave(cases,cases_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "cases values: "<< cases << std::endl;
  IntegerVector activities  = RcppDeepState_IntegerVector();
  std::string activities_t = "/home/akhila/fuzzer_packages/fuzzedpackages/processmapR/inst/testfiles/count_precedence/AFL_count_precedence/afl_inputs/" + std::to_string(t) + "_activities.qs";
  qs::c_qsave(activities,activities_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "activities values: "<< activities << std::endl;
  IntegerVector lead(1);
  lead[0]  = RcppDeepState_int();
  std::string lead_t = "/home/akhila/fuzzer_packages/fuzzedpackages/processmapR/inst/testfiles/count_precedence/AFL_count_precedence/afl_inputs/" + std::to_string(t) + "_lead.qs";
  qs::c_qsave(lead,lead_t,
		"high", "zstd", 1, 15, true, 1);
  std::cout << "lead values: "<< lead << std::endl;
  std::cout << "input ends" << std::endl;
  try{
    count_precedence(cases,activities,lead[0]);
  }
  catch(Rcpp::exception& e){
    std::cout<<"Exception Handled"<<std::endl;
  }
}
